io.write("what is one point given that's on the circle?")
pt1 = io.read("*n")
io.write("what is the second point given that's on the circle? ")
pt2 = io.read("*n")
io.write("what is the last point given that's on the circle? ")
pt3 = io.read("*n")
